# -*- coding: utf-8 -*-
"""Untitled184.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132trco3skZqoVVL5TVBfFfiPdH4Y2X-5
"""



import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.plotting import plot_decision_regions

df =pd.read_excel("/content/pacement_dataset.xlsx")

df.head()

df.isnull().sum()



df.columns = df.columns.str.strip()
sns.scatterplot(x="cgpa",y="company_score",data=df,hue="placed_student")
plt.show( )

# these data are the classification nature and also belong to the linearly separable

x=df.iloc[:,:-1]
y=df["placed_student"]

from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train ,y_test =train_test_split(x,y ,test_size =0.3 ,random_state =42)

from sklearn.svm import SVC



svc1 =SVC(kernel="poly")
ans =svc1.fit(x_train ,y_train)



(ans.score(x_train ,y_train))*100

(ans.score(x_test ,y_test))*100

plot_decision_regions(x.to_numpy(),y.to_numpy(),clf=svc1)
 plt.show()

# in the svm algorithm inside hard margin and soft margin will came  hard margin are used when dataset will
# belong the linear separable and soft margin non linear separable in hars=d marhin kernel of we will used
# kernel =[linear, polynomial sis=gmoid]

# on there data linear   separable there  are not   missclassification will came